Addition of version number to about.go
pesos/grofer pull request #125
Opened 2021-06-09 14:51 UTC by 7wik-pk

# Description

Version number is added as a hardcoded string (```groferVersion```) to ```About.text``` within the ```About``` widget, but it isn't initialized. While building, the version must be injected (as a string) to the package level variable ```groferVersion``` to avoid display of an empty string in place of version.

Fixes #117 

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [ ] I have read the [contribution guidelines](https://github.com/pesos/grofer/blob/master/CONTRIBUTING.md) and followed it as far as possible. 
- [ ] I have performed a self-review of my own code (if applicable)
- [x] I have commented my code, particularly in hard-to-understand areas (if applicable)
- [ ] I have run `go fmt` on my code ([reference](https://blog.golang.org/gofmt))
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] My changes generate no new warnings 
- [ ] Any dependent and pending changes have been merged and published

2021-06-10 08:24 UTC, Samyak2 requested changes
It appears that you indeed did not manage to break the code by adding 3 lines xD, It works well!

Thanks for the typo fix too.

Though, as we discussed in the issue, it would be better to hardcode the version here. Without this, the version would only be available in the release binaries and not (for example) when installed through `go get`. We would have to change this on every release, but that's okay as long as it is documented in the release process.

2021-06-10 08:44 UTC, 7wik-pk commented
righto, I've initialized groferVersion to 1.3.0 for now.

2021-06-10 14:34 UTC, Samyak2 approved these changes
LGTM!

2021-06-11 18:51 UTC, Gituser143 approved these changes

2021-06-11 18:52 UTC, Gituser143 commented
@7wik-pk Thank you for your contribution! I'll let either @Samyak2 or @MadhavJivrajani merge this.

2021-06-11 21:04 UTC, merged